workflows:
  android_and_web:
    name: Android ve Web build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Proje yapisini olustur
        script: |
          flutter create . --platforms=android,web

      - name: Paketleri indir
        script: |
          flutter pub get

      - name: Android APK olustur
        script: |
          flutter build apk --debug

      - name: Web build olustur
        script: |
          flutter build web --release

    artifacts:
      - build/app/outputs/**/*.apk
      - build/web/**
