workflows:
  flutter-android:
    name: Hizmet Demo Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Proje dosyalarını tamamla
        script: flutter create .
      - name: Flutter paketlerini yükle
        script: flutter pub get
      - name: APK oluştur
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    cache:
      cache_paths:
        - ~/.pub-cache
