workflows:
  android_and_web:
    name: Android ve Web build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Temiz proje platform klasörleri oluştur
        script: |
          rm -rf android
          rm -rf web
          flutter create . --platforms=android,web

      - name: Paketleri indir
        script: flutter pub get

      - name: Android APK oluştur
        script: flutter build apk --debug

      - name: Web build oluştur
        script: flutter build web --release

    artifacts:
      - build/app/outputs/**/*.apk
      - build/web/**
